In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Type 1 - Stacked Ensemble

In [3]:
import pandas as pd

In [28]:
dataset = pd.read_csv("/content/drive/MyDrive/Heart Dataset/heart.csv")

In [11]:
dataset.columns = ['age', 'sex', 'chest_pain_type', 'resting_blood_pressure', 'cholesterol', 'fasting_blood_sugar', 'rest_ecg', 'max_heart_rate_achieved',
       'exercise_induced_angina', 'st_depression', 'st_slope', 'num_major_vessels', 'thalassemia', 'condition']

In [15]:
test0 = dataset.sample(frac = 0.2)

train0 = dataset.drop(test0.index)

test0.to_csv("/content/drive/MyDrive/Heart Dataset/test1.csv")
train0.to_csv("/content/drive/MyDrive/Heart Dataset/train1.csv")

In [6]:
!pip install requests
!pip install tabulate
!pip install "colorama>=0.3.8"
!pip install future

Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (2.23.0)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests) (2021.5.30)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (0.8.9)
Collecting colorama>=0.3.8
  Downloading https://files.pythonhosted.org/packages/44/98/5b86278fbbf250d239ae0ecb724f8572af1c91f4a11edf4d36a206189440/colorama-0.4.4-py2.py3-none-any.whl
Installing collected packages: colorama
Successfully installed colorama-0.4.4
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (0.16.0)

In [7]:
!pip install -f http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html h2o

Looking in links: http://h2o-release.s3.amazonaws.com/h2o/latest_stable_Py.html
WARNING: The repository located at h2o-release.s3.amazonaws.com is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host h2o-release.s3.amazonaws.com'.
Collecting h2o
  Downloading https://files.pythonhosted.org/packages/8c/6a/0ee4e2387e31cb472a952a44cffd72f1b471c51f28f0ceeeaa5e4709be1b/h2o-3.32.1.4.tar.gz (164.8MB)
     |████████████████████████████████| 164.8MB 77kB/s
Requirement already satisfied: requests in /usr/local/lib/python3.7/dist-packages (from h2o) (2.23.0)
Requirement already satisfied: tabulate in /usr/local/lib/python3.7/dist-packages (from h2o) (0.8.9)
Requirement already satisfied: future in /usr/local/lib/python3.7/dist-packages (from h2o) (0.16.0)
Requirement already satisfied: colorama>=0.3.8 in /usr/local/lib/python3.7/dist-packages (from h2o) (0.4.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (1.24.3)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2021.5.30)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests->h2o) (3.0.4)
Building wheels for collected packages: h2o
  Building wheel for h2o (setup.py) ... done
  Created wheel for h2o: filename=h2o-3.32.1.4-py2.py3-none-any.whl size=164871668 sha256=c06a18056f45465168705af3511ab8eb3b3b206a7e1c1887171e5f4f92aed325
  Stored in directory: /root/.cache/pip/wheels/67/76/54/89d7711536d5bb0d010bf35a34deca3eddc757efba78dbc74f
Successfully built h2o
Installing collected packages: h2o
Successfully installed h2o-3.32.1.4

In [18]:
import h2o
from h2o.automl import H2OAutoML

h2o.init()

train = h2o.import_file("/content/drive/MyDrive/Heart Dataset/train1.csv")
test = h2o.import_file("/content/drive/MyDrive/Heart Dataset/test1.csv")

# Identify predictors and response
x = train.columns
y = "condition"
x.remove(y)

# For binary classification, response should be a factor
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

# Run AutoML for 20 base models (limited to 1 hour max runtime by default)
aml = H2OAutoML(max_models=20, seed=1)
aml.train(x=x, y=y, training_frame=train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)  # Print all rows instead of default (10 rows)

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         4 mins 47 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.4
H2O_cluster_version_age:    6 days
H2O_cluster_name:           H2O_from_python_unknownUser_e86ayq
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.160 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
AutoML progress: |████████████████
08:43:25.926: GBM_5_AutoML_20210715_084226 [GBM def_5] failed: water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for GBM model: GBM_5_AutoML_20210715_084226.  Details: ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 193.0.
ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 193.0.
ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 194.0.
ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 194.0.
ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 194.0.


████████████████████████████████████████| 100%

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
StackedEnsemble_BestOfFamily_AutoML_20210715_084226,1,0.000845679,1,0,0.000871328,7.59213e-07
XGBoost_grid__1_AutoML_20210715_084226_model_1,1,0.198469,1,0,0.182451,0.0332884
XGBoost_grid__1_AutoML_20210715_084226_model_5,1,0.0142743,1,0,0.0163306,0.000266689
GBM_3_AutoML_20210715_084226,1,3.60318e-15,1,0,3.60564e-14,1.30006e-27
XGBoost_grid__1_AutoML_20210715_084226_model_2,1,0.0837963,1,0,0.0845007,0.00714037
DRF_1_AutoML_20210715_084226,1,0.108351,1,0,0.139197,0.0193758
GBM_grid__1_AutoML_20210715_084226_model_1,1,7.30775e-08,1,0,1.12297e-06,1.26105e-12
GBM_grid__1_AutoML_20210715_084226_model_2,1,5.05106e-16,1,0,3.19067e-15,1.01804e-29
XGBoost_1_AutoML_20210715_084226,1,0.0811795,1,0,0.0850101,0.00722671
XGBoost_2_AutoML_20210715_084226,1,0.199109,1,0,0.19084,0.0364198
GBM_1_AutoML_20210715_084226,1,1.01568e-12,1,0,1.33364e-11,1.7786e-22
XRT_1_AutoML_20210715_084226,1,0.0930965,1,0,0.111017,0.0123249
GBM_2_AutoML_20210715_084226,1,1.91628e-15,1,0,1.67363e-14,2.80103e-28
GBM_4_AutoML_20210715_084226,1,2.20668e-15,1,0,2.01401e-14,4.05622e-28
StackedEnsemble_AllModels_AutoML_20210715_084226,1,0.0664622,1,0,0.064547,0.00416631
XGBoost_grid__1_AutoML_20210715_084226_model_3,1,0.0103,1,0,0.0103145,0.000106389
XGBoost_3_AutoML_20210715_084226,1,0.0403627,1,0,0.0490653,0.0024074
DeepLearning_grid__2_AutoML_20210715_084226_model_1,0.998281,0.0680488,0.998601,0.0152672,0.145824,0.0212645
DeepLearning_grid__1_AutoML_20210715_084226_model_1,0.998143,0.100697,0.99843,0.0225225,0.155221,0.0240937
GLM_1_AutoML_20210715_084226,0.997593,0.0655263,0.997941,0.0263393,0.138644,0.0192222
DeepLearning_1_AutoML_20210715_084226,0.966784,0.2359,0.976077,0.0800839,0.267824,0.0717295
XGBoost_grid__1_AutoML_20210715_084226_model_4,0.894849,0.596714,0.919901,0.21797,0.450064,0.202558

In [19]:
aml.leader

Model Details
=============
H2OStackedEnsembleEstimator :  Stacked Ensemble
Model Key:  StackedEnsemble_BestOfFamily_AutoML_20210715_084226

No model summary for this model

ModelMetricsBinomialGLM: stackedensemble
** Reported on train data. **

MSE: 4.0488401487070933e-07
RMSE: 0.0006363049700188655
LogLoss: 0.0006287475242653332
Null degrees of freedom: 241
Residual degrees of freedom: 239
Null deviance: 333.8284560897962
Residual deviance: 0.3043138017444027
AIC: 6.304313801744403
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9990560262619319:

              0      1 Error          Rate
0      0  111.0    0.0   0.0   (0.0/111.0)
1      1    0.0  131.0   0.0   (0.0/131.0)
2  Total  111.0  131.0   0.0   (0.0/242.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold      value   idx
0                        max f1   0.999056    1.00000  39.0
1                        max f2   0.999056    1.00000  39.0
2                  max f0point5   0.999056    1.00000  39.0
3                  max accuracy   0.999056    1.00000  39.0
4                 max precision   0.999463    1.00000   0.0
5                    max recall   0.999056    1.00000  39.0
6               max specificity   0.999463    1.00000   0.0
7              max absolute_mcc   0.999056    1.00000  39.0
8    max min_per_class_accuracy   0.999056    1.00000  39.0
9   max mean_per_class_accuracy   0.999056    1.00000  39.0
10                      max tns   0.999463  111.00000   0.0
11                      max fns   0.999463   39.00000   0.0
12                      max fps   0.000647  111.00000  52.0
13                      max tps   0.999056  131.00000  39.0
14                      max tnr   0.999463    1.00000   0.0
15                      max fnr   0.999463    0.29771   0.0
16                      max fpr   0.000647    1.00000  52.0
17                      max tpr   0.999056    1.00000  39.0

Gains/Lift Table: Avg response rate: 54.13 %, avg score: 54.13 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.380165  ...        84.732824            0.702290
1      2                  0.400826  ...        84.732824            0.740458
2      3                  0.500000  ...        84.732824            0.923664
3      4                  1.000000  ...         0.000000            0.000000

[4 rows x 14 columns]

ModelMetricsBinomialGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 7.592130370217524e-07
RMSE: 0.0008713283175828456
LogLoss: 0.0008456794174557166
Null degrees of freedom: 241
Residual degrees of freedom: 239
Null deviance: 334.99061771601885
Residual deviance: 0.409308838048566
AIC: 6.409308838048566
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9983482393836338:

              0      1 Error          Rate
0      0  111.0    0.0   0.0   (0.0/111.0)
1      1    0.0  131.0   0.0   (0.0/131.0)
2  Total  111.0  131.0   0.0   (0.0/242.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold       value   idx
0                        max f1   0.998348    1.000000  52.0
1                        max f2   0.998348    1.000000  52.0
2                  max f0point5   0.998348    1.000000  52.0
3                  max accuracy   0.998348    1.000000  52.0
4                 max precision   0.999369    1.000000   0.0
5                    max recall   0.998348    1.000000  52.0
6               max specificity   0.999369    1.000000   0.0
7              max absolute_mcc   0.998348    1.000000  52.0
8    max min_per_class_accuracy   0.998348    1.000000  52.0
9   max mean_per_class_accuracy   0.998348    1.000000  52.0
10                      max tns   0.999369  111.000000   0.0
11                      max fns   0.999369  116.000000   0.0
12                      max fps   0.000763  111.000000  96.0
13                      max tps   0.998348  131.000000  52.0
14                      max tnr   0.999369    1.000000   0.0
15                      max fnr   0.999369    0.885496   0.0
16                      max fpr   0.000763    1.000000  96.0
17                      max tpr   0.998348    1.000000  52.0

Gains/Lift Table: Avg response rate: 54.13 %, avg score: 54.13 %

    group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0       1                  0.061983  ...        84.732824            0.114504
1       2                  0.111570  ...        84.732824            0.206107
2       3                  0.177686  ...        84.732824            0.328244
3       4                  0.272727  ...        84.732824            0.503817
4       5                  0.355372  ...        84.732824            0.656489
5       6                  0.400826  ...        84.732824            0.740458
6       7                  0.500000  ...        84.732824            0.923664
7       8                  0.599174  ...        66.896552            0.873874
8       9                  0.743802  ...        34.444444            0.558559
9      10                  0.818182  ...        22.222222            0.396396
10     11                  0.938017  ...         6.607930            0.135135
11     12                  1.000000  ...         0.000000            0.000000

[12 rows x 14 columns]

In [22]:
import h2o
from h2o.estimators.random_forest import H2ORandomForestEstimator
from h2o.estimators.gbm import H2OGradientBoostingEstimator
from h2o.estimators.stackedensemble import H2OStackedEnsembleEstimator
from h2o.grid.grid_search import H2OGridSearch
from __future__ import print_function
h2o.init()

# Import a sample binary outcome train/test set into H2O
train = h2o.import_file("/content/drive/MyDrive/Heart Dataset/train1.csv")
test = h2o.import_file("/content/drive/MyDrive/Heart Dataset/test1.csv")

# Identify predictors and response
x = train.columns
y = "condition"
x.remove(y)

# For binary classification, response should be a factor
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

# Number of CV folds (to generate level-one data for stacking)
nfolds = 5

# Train and cross-validate a GBM
my_gbm = H2OGradientBoostingEstimator(distribution="bernoulli",
                                      ntrees=10,
                                      max_depth=3,
                                      min_rows=2,
                                      learn_rate=0.2,
                                      nfolds=nfolds,
                                      fold_assignment="Modulo",
                                      keep_cross_validation_predictions=True,
                                      seed=1)
my_gbm.train(x=x, y=y, training_frame=train)


# Train and cross-validate a RF
my_rf = H2ORandomForestEstimator(ntrees=50,
                                 nfolds=nfolds,
                                 fold_assignment="Modulo",
                                 keep_cross_validation_predictions=True,
                                 seed=1)
my_rf.train(x=x, y=y, training_frame=train)


# Train a stacked ensemble using the GBM and GLM above
ensemble = H2OStackedEnsembleEstimator(model_id="my_ensemble_binomial",
                                       base_models=[my_gbm, my_rf])
ensemble.train(x=x, y=y, training_frame=train)

# Eval ensemble performance on the test data
perf_stack_test = ensemble.model_performance(test)

# Compare to base learner performance on the test set
perf_gbm_test = my_gbm.model_performance(test)
perf_rf_test = my_rf.model_performance(test)
baselearner_best_auc_test = max(perf_gbm_test.auc(), perf_rf_test.auc())
stack_auc_test = perf_stack_test.auc()
print("Best Base-learner Test AUC:  {0}".format(baselearner_best_auc_test))
print("Ensemble Test AUC:  {0}".format(stack_auc_test))

# Generate predictions on a test set (if neccessary)
pred = ensemble.predict(test)

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         21 mins 31 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.4
H2O_cluster_version_age:    6 days
H2O_cluster_name:           H2O_from_python_unknownUser_e86ayq
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.057 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
drf Model Build progress: |███████████████████████████████████████████████| 100%
stackedensemble Model Build progress: |███████████████████████████████████| 100%
Best Base-learner Test AUC:  1.0
Ensemble Test AUC:  1.0
stackedensemble prediction progress: |████████████████████████████████████| 100%

In [23]:
perf_stack_test

ModelMetricsBinomialGLM: stackedensemble
** Reported on test data. **

MSE: 2.176736037589438e-05
RMSE: 0.004665550382955304
LogLoss: 0.0037261175657954835
Null degrees of freedom: 60
Residual degrees of freedom: 58
Null deviance: 83.82235374257142
Residual deviance: 0.4545863430270511
AIC: 6.454586343027051
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9892970383767159:

             0     1 Error         Rate
0      0  27.0   0.0   0.0   (0.0/27.0)
1      1   0.0  34.0   0.0   (0.0/34.0)
2  Total  27.0  34.0   0.0   (0.0/61.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold      value   idx
0                        max f1   0.989297   1.000000   8.0
1                        max f2   0.989297   1.000000   8.0
2                  max f0point5   0.989297   1.000000   8.0
3                  max accuracy   0.989297   1.000000   8.0
4                 max precision   0.997975   1.000000   0.0
5                    max recall   0.989297   1.000000   8.0
6               max specificity   0.997975   1.000000   0.0
7              max absolute_mcc   0.989297   1.000000   8.0
8    max min_per_class_accuracy   0.989297   1.000000   8.0
9   max mean_per_class_accuracy   0.989297   1.000000   8.0
10                      max tns   0.997975  27.000000   0.0
11                      max fns   0.997975  22.000000   0.0
12                      max fps   0.002184  27.000000  20.0
13                      max tps   0.989297  34.000000   8.0
14                      max tnr   0.997975   1.000000   0.0
15                      max fnr   0.997975   0.647059   0.0
16                      max fpr   0.002184   1.000000  20.0
17                      max tpr   0.989297   1.000000   8.0

Gains/Lift Table: Avg response rate: 55.74 %, avg score: 55.78 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.196721  ...        79.411765            0.352941
1      2                  0.278689  ...        79.411765            0.500000
2      3                  0.360656  ...        79.411765            0.647059
3      4                  0.459016  ...        79.411765            0.823529
4      5                  0.508197  ...        79.411765            0.911765
5      6                  0.606557  ...        64.864865            0.888889
6      7                  0.737705  ...        35.555556            0.592593
7      8                  0.803279  ...        24.489796            0.444444
8      9                  0.918033  ...         8.928571            0.185185
9     10                  1.000000  ...         0.000000            0.000000

[10 rows x 14 columns]

In [25]:
perf_gbm_test

ModelMetricsBinomial: gbm
** Reported on test data. **

MSE: 0.003946836347623337
RMSE: 0.06282385174138352
LogLoss: 0.06471315154768567
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9414834246584274:

             0     1 Error         Rate
0      0  27.0   0.0   0.0   (0.0/27.0)
1      1   0.0  34.0   0.0   (0.0/34.0)
2  Total  27.0  34.0   0.0   (0.0/61.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold  value  idx
0                        max f1   0.941483    1.0  0.0
1                        max f2   0.941483    1.0  0.0
2                  max f0point5   0.941483    1.0  0.0
3                  max accuracy   0.941483    1.0  0.0
4                 max precision   0.941483    1.0  0.0
5                    max recall   0.941483    1.0  0.0
6               max specificity   0.941483    1.0  0.0
7              max absolute_mcc   0.941483    1.0  0.0
8    max min_per_class_accuracy   0.941483    1.0  0.0
9   max mean_per_class_accuracy   0.941483    1.0  0.0
10                      max tns   0.941483   27.0  0.0
11                      max fns   0.941483    0.0  0.0
12                      max fps   0.067860   27.0  1.0
13                      max tps   0.941483   34.0  0.0
14                      max tnr   0.941483    1.0  0.0
15                      max fnr   0.941483    0.0  0.0
16                      max fpr   0.067860    1.0  1.0
17                      max tpr   0.941483    1.0  0.0

Gains/Lift Table: Avg response rate: 55.74 %, avg score: 55.48 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.557377  ...        79.411765                 1.0
1      2                  1.000000  ...         0.000000                 0.0

[2 rows x 14 columns]

In [26]:
perf_rf_test

ModelMetricsBinomial: drf
** Reported on test data. **

MSE: 0.013075409836065574
RMSE: 0.11434775833423921
LogLoss: 0.08328103025118098
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.7:

             0     1 Error         Rate
0      0  27.0   0.0   0.0   (0.0/27.0)
1      1   0.0  34.0   0.0   (0.0/34.0)
2  Total  27.0  34.0   0.0   (0.0/61.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold      value   idx
0                        max f1        0.7   1.000000   8.0
1                        max f2        0.7   1.000000   8.0
2                  max f0point5        0.7   1.000000   8.0
3                  max accuracy        0.7   1.000000   8.0
4                 max precision        1.0   1.000000   0.0
5                    max recall        0.7   1.000000   8.0
6               max specificity        1.0   1.000000   0.0
7              max absolute_mcc        0.7   1.000000   8.0
8    max min_per_class_accuracy        0.7   1.000000   8.0
9   max mean_per_class_accuracy        0.7   1.000000   8.0
10                      max tns        1.0  27.000000   0.0
11                      max fns        1.0  22.000000   0.0
12                      max fps        0.0  27.000000  20.0
13                      max tps        0.7  34.000000   8.0
14                      max tnr        1.0   1.000000   0.0
15                      max fnr        1.0   0.647059   0.0
16                      max fpr        0.0   1.000000  20.0
17                      max tpr        0.7   1.000000   8.0

Gains/Lift Table: Avg response rate: 55.74 %, avg score: 57.18 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.196721  ...        79.411765            0.352941
1      2                  0.278689  ...        79.411765            0.500000
2      3                  0.360656  ...        79.411765            0.647059
3      4                  0.459016  ...        79.411765            0.823529
4      5                  0.508197  ...        79.411765            0.911765
5      6                  0.606557  ...        64.864865            0.888889
6      7                  0.737705  ...        35.555556            0.592593
7      8                  0.803279  ...        24.489796            0.444444
8      9                  0.918033  ...         8.928571            0.185185
9     10                  1.000000  ...         0.000000            0.000000

[10 rows x 14 columns]

In [24]:
pred

predict,p0,p1
0,0.997559,0.00244091
1,0.00202486,0.997975
1,0.010703,0.989297
0,0.996951,0.00304935
0,0.997816,0.00218375
1,0.00492959,0.99507
0,0.995743,0.00425658
0,0.996592,0.00340808
1,0.00202486,0.997975
1,0.00353215,0.996468

# Type 2 - Gradient Boosting

In [29]:
dataset = pd.read_csv("/content/drive/MyDrive/Heart Dataset/heart.csv")

In [31]:
import h2o
from h2o.automl import H2OAutoML

h2o.init()

train = h2o.import_file("/content/drive/MyDrive/Heart Dataset/train.csv")
test = h2o.import_file("/content/drive/MyDrive/Heart Dataset/test.csv")

# Identify predictors and response
x = train.columns
y = "target"
x.remove(y)

# For binary classification, response should be a factor
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

# Run AutoML for 20 base models (limited to 1 hour max runtime by default)
aml = H2OAutoML(max_models=20, seed=1)
aml.train(x=x, y=y, training_frame=train)

# View the AutoML Leaderboard
lb = aml.leaderboard
lb.head(rows=lb.nrows)  # Print all rows instead of default (10 rows)

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         27 mins 14 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.4
H2O_cluster_version_age:    6 days
H2O_cluster_name:           H2O_from_python_unknownUser_e86ayq
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.054 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
AutoML progress: |████████████████
09:06:43.524: Skipping training of model GBM_5_AutoML_20210715_090453 due to exception: water.exceptions.H2OModelBuilderIllegalArgumentException: Illegal argument(s) for GBM model: GBM_5_AutoML_20210715_090453.  Details: ERRR on field: _min_rows: The dataset size is too small to split for min_rows=100.0: must have at least 200.0 (weighted) rows, but have only 194.0.


████████████████████████████████████████| 100%

model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
GBM_2_AutoML_20210715_090453,1,0.0157143,1,0,0.0679615,0.00461876
GBM_3_AutoML_20210715_090453,1,0.0223791,1,0,0.0706829,0.00499608
GBM_4_AutoML_20210715_090453,1,0.0184897,1,0,0.0694906,0.00482895
XGBoost_3_AutoML_20210715_090453,1,0.0595412,1,0,0.0831564,0.00691499
XGBoost_grid__1_AutoML_20210715_090453_model_1,1,0.277268,1,0,0.251558,0.0632816
StackedEnsemble_BestOfFamily_AutoML_20210715_090453,1,0.0092131,1,0,0.0480518,0.00230897
XGBoost_grid__1_AutoML_20210715_090453_model_5,1,0.028681,1,0,0.0669706,0.00448506
StackedEnsemble_AllModels_AutoML_20210715_090453,1,0.0940214,1,0,0.110644,0.0122422
GBM_grid__1_AutoML_20210715_090453_model_2,1,0.0168049,1,0,0.0676693,0.00457913
GBM_grid__1_AutoML_20210715_090453_model_1,1,0.00942226,1,0,0.0595754,0.00354923
GBM_1_AutoML_20210715_090453,0.999893,0.0204219,0.999906,0.00549451,0.0702181,0.00493058
XRT_1_AutoML_20210715_090453,0.999787,0.120431,0.999815,0.00485437,0.153872,0.0236765
XGBoost_grid__1_AutoML_20210715_090453_model_2,0.999573,0.144893,0.999635,0.00485437,0.161218,0.0259912
DRF_1_AutoML_20210715_090453,0.99952,0.10942,0.999592,0.00485437,0.14641,0.0214359
XGBoost_1_AutoML_20210715_090453,0.99904,0.117692,0.999216,0.00485437,0.134263,0.0180266
DeepLearning_grid__1_AutoML_20210715_090453_model_1,0.998826,0.0535136,0.998988,0.0145631,0.128041,0.0163945
XGBoost_grid__1_AutoML_20210715_090453_model_3,0.99776,0.0340641,0.99835,0.00485437,0.0720074,0.00518507
DeepLearning_grid__2_AutoML_20210715_090453_model_1,0.997226,0.09858,0.997674,0.0268324,0.165292,0.0273214
XGBoost_2_AutoML_20210715_090453,0.997226,0.242085,0.998038,0.00485437,0.218563,0.04777
GLM_1_AutoML_20210715_090453,0.996906,0.0908453,0.997433,0.0200576,0.154015,0.0237206
DeepLearning_1_AutoML_20210715_090453,0.974501,0.211837,0.979482,0.0643871,0.252277,0.0636439
XGBoost_grid__1_AutoML_20210715_090453_model_4,0.489811,0.691438,0.522235,0.5,0.499145,0.249146

In [32]:
aml.leader

Model Details
=============
H2OGradientBoostingEstimator :  Gradient Boosting Machine
Model Key:  GBM_2_AutoML_20210715_090453


Model Summary:

     number_of_trees  ...  max_leaves  mean_leaves
0              406.0  ...        14.0    12.044335

[1 rows x 10 columns]

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 6.576594096281164e-31
RMSE: 8.109620272417916e-16
LogLoss: 5.259252369229482e-16
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9999999999999996:

            -1      0 Error          Rate
0     -1  91.0    0.0   0.0    (0.0/91.0)
1      0   0.0  103.0   0.0   (0.0/103.0)
2  Total  91.0  103.0   0.0   (0.0/194.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric     threshold  value   idx
0                        max f1  1.000000e+00    1.0   0.0
1                        max f2  1.000000e+00    1.0   0.0
2                  max f0point5  1.000000e+00    1.0   0.0
3                  max accuracy  1.000000e+00    1.0   0.0
4                 max precision  1.000000e+00    1.0   0.0
5                    max recall  1.000000e+00    1.0   0.0
6               max specificity  1.000000e+00    1.0   0.0
7              max absolute_mcc  1.000000e+00    1.0   0.0
8    max min_per_class_accuracy  1.000000e+00    1.0   0.0
9   max mean_per_class_accuracy  1.000000e+00    1.0   0.0
10                      max tns  1.000000e+00   91.0   0.0
11                      max fns  1.000000e+00    0.0   0.0
12                      max fps  1.376496e-17   91.0  91.0
13                      max tps  1.000000e+00  103.0   0.0
14                      max tnr  1.000000e+00    1.0   0.0
15                      max fnr  1.000000e+00    0.0   0.0
16                      max fpr  1.376496e-17    1.0  91.0
17                      max tpr  1.000000e+00    1.0   0.0

Gains/Lift Table: Avg response rate: 53.09 %, avg score: 53.09 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.139175  ...        88.349515            0.262136
1      2                  0.283505  ...        88.349515            0.533981
2      3                  0.376289  ...        88.349515            0.708738
3      4                  0.412371  ...        88.349515            0.776699
4      5                  0.505155  ...        88.349515            0.951456
5      6                  0.597938  ...        67.241379            0.857143
6      7                  0.701031  ...        42.647059            0.637363
7      8                  0.798969  ...        25.161290            0.428571
8      9                  0.896907  ...        11.494253            0.219780
9     10                  1.000000  ...         0.000000            0.000000

[10 rows x 14 columns]

ModelMetricsBinomial: gbm
** Reported on cross-validation data. **

MSE: 0.004618759291984383
RMSE: 0.06796145445754073
LogLoss: 0.015714298423743906
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.05382167152730165:

            -1      0 Error          Rate
0     -1  91.0    0.0   0.0    (0.0/91.0)
1      0   0.0  103.0   0.0   (0.0/103.0)
2  Total  91.0  103.0   0.0   (0.0/194.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric     threshold       value    idx
0                        max f1  5.382167e-02    1.000000   21.0
1                        max f2  5.382167e-02    1.000000   21.0
2                  max f0point5  5.382167e-02    1.000000   21.0
3                  max accuracy  5.382167e-02    1.000000   21.0
4                 max precision  1.000000e+00    1.000000    0.0
5                    max recall  5.382167e-02    1.000000   21.0
6               max specificity  1.000000e+00    1.000000    0.0
7              max absolute_mcc  5.382167e-02    1.000000   21.0
8    max min_per_class_accuracy  5.382167e-02    1.000000   21.0
9   max mean_per_class_accuracy  5.382167e-02    1.000000   21.0
10                      max tns  1.000000e+00   91.000000    0.0
11                      max fns  1.000000e+00   21.000000    0.0
12                      max fps  1.000000e-19   91.000000  102.0
13                      max tps  5.382167e-02  103.000000   21.0
14                      max tnr  1.000000e+00    1.000000    0.0
15                      max fnr  1.000000e+00    0.203883    0.0
16                      max fpr  1.000000e-19    1.000000  102.0
17                      max tpr  5.382167e-02    1.000000   21.0

Gains/Lift Table: Avg response rate: 53.09 %, avg score: 52.62 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.237113  ...        88.349515            0.446602
1      2                  0.314433  ...        88.349515            0.592233
2      3                  0.402062  ...        88.349515            0.757282
3      4                  0.500000  ...        88.349515            0.941748
4      5                  0.597938  ...        67.241379            0.857143
5      6                  0.701031  ...        42.647059            0.637363
6      7                  0.798969  ...        25.161290            0.428571
7      8                  0.896907  ...        11.494253            0.219780
8      9                  1.000000  ...         0.000000            0.000000

[9 rows x 14 columns]

Cross-Validation Metrics Summary:

                                     mean  ...     cv_4_valid     cv_5_valid
0                  accuracy           1.0  ...            1.0            1.0
1                       auc           1.0  ...            1.0            1.0
2                       err           0.0  ...            0.0            0.0
3                 err_count           0.0  ...            0.0            0.0
4                  f0point5           1.0  ...            1.0            1.0
5                        f1           1.0  ...            1.0            1.0
6                        f2           1.0  ...            1.0            1.0
7            lift_top_group     1.8842857  ...           1.95            1.9
8                   logloss   0.015633712  ...  5.7333056E-15   1.183264E-15
9       max_per_class_error           0.0  ...            0.0            0.0
10                      mcc           1.0  ...            1.0            1.0
11  mean_per_class_accuracy           1.0  ...            1.0            1.0
12     mean_per_class_error           0.0  ...            0.0            0.0
13                      mse  0.0045950734  ...   9.853467E-28  2.2884426E-29
14                   pr_auc           1.0  ...            1.0            1.0
15                precision           1.0  ...            1.0            1.0
16                       r2     0.9815103  ...            1.0            1.0
17                   recall           1.0  ...            1.0            1.0
18                     rmse   0.030315254  ...   3.139023E-14   4.783767E-15
19              specificity           1.0  ...            1.0            1.0

[20 rows x 8 columns]

Scoring History:

                timestamp  ... training_lift  training_classification_error
0     2021-07-15 09:05:49  ...      1.000000                       0.469072
1     2021-07-15 09:05:50  ...      1.883495                       0.030928
2     2021-07-15 09:05:50  ...      1.883495                       0.000000
3     2021-07-15 09:05:50  ...      1.883495                       0.000000
4     2021-07-15 09:05:50  ...      1.883495                       0.000000
5     2021-07-15 09:05:50  ...      1.883495                       0.000000
6     2021-07-15 09:05:50  ...      1.883495                       0.000000
7     2021-07-15 09:05:50  ...      1.883495                       0.000000
8     2021-07-15 09:05:50  ...      1.883495                       0.000000
9     2021-07-15 09:05:50  ...      1.883495                       0.000000
10    2021-07-15 09:05:50  ...      1.883495                       0.000000
11    2021-07-15 09:05:50  ...      1.883495                       0.000000
12    2021-07-15 09:05:50  ...      1.883495                       0.000000
13    2021-07-15 09:05:50  ...      1.883495                       0.000000
14    2021-07-15 09:05:50  ...      1.883495                       0.000000
15    2021-07-15 09:05:50  ...      1.883495                       0.000000
16    2021-07-15 09:05:50  ...      1.883495                       0.000000
17    2021-07-15 09:05:50  ...      1.883495                       0.000000
18    2021-07-15 09:05:50  ...      1.883495                       0.000000
19    2021-07-15 09:05:50  ...      1.883495                       0.000000

[20 rows x 10 columns]

See the whole table with table.as_data_frame()

Variable Importances:

             variable  relative_importance  scaled_importance  percentage
0                  C1           158.712936           1.000000    0.633494
1            exang_ca            24.071236           0.151665    0.096079
2        sex_oldpeak2            16.769825           0.105661    0.066936
3                  cp            10.653898           0.067127    0.042524
4              sex_ca             8.837059           0.055680    0.035273
5      exang_oldpeak2             5.677562           0.035773    0.022662
6       thal_oldpeak2             3.873807           0.024408    0.015462
7         exang_chol2             3.581711           0.022567    0.014296
8              fbs_ca             2.698549           0.017003    0.010771
9         exang_slope             2.445454           0.015408    0.009761
10           exang_cp             1.899287           0.011967    0.007581
11             fbs_cp             1.559957           0.009829    0.006226
12         restecg_cp             1.548674           0.009758    0.006181
13         thal_chol2             1.333104           0.008399    0.005321
14       fbs_oldpeak2             1.277469           0.008049    0.005099
15      age2_oldpeak2             1.215060           0.007656    0.004850
16            thalach             1.023767           0.006450    0.004086
17           trestbps             1.022814           0.006444    0.004083
18  restecg_trestbps2             0.768398           0.004841    0.003067
19                age             0.530338           0.003341    0.002117

See the whole table with table.as_data_frame()

In [35]:
import h2o
from h2o.estimators import H2OGradientBoostingEstimator
h2o.init()

# Import the prostate dataset into H2O:
train = h2o.import_file("/content/drive/MyDrive/Heart Dataset/train.csv")
test = h2o.import_file("/content/drive/MyDrive/Heart Dataset/test.csv")

# Set the predictors and response; set the factors:
train["target"] = train["target"].asfactor()
predictors = ["C1","exang_ca","sex_oldpeak2","cp","sex_ca","exang_oldpeak2","thal_oldpeak2","exang_chol2","fbs_ca", "exang_slope", "exang_cp", "fbs_cp", "restecg_cp", "thal_chol2", "fbs_oldpeak2", "age2_oldpeak2", "thalach", "trestbps", "restecg_trestbps2", "age"]
response = "target"

# Build and train the model:
heart_gbm = H2OGradientBoostingEstimator(nfolds=5,
                                        seed=1111,
                                        keep_cross_validation_predictions = True)
heart_gbm.train(x=predictors, y=response, training_frame=train)

# Eval performance:
perf = heart_gbm.model_performance()

# Generate predictions on a test set (if necessary):
pred = heart_gbm.predict(test)

# Extract feature interactions:
feature_interactions = heart_gbm.feature_interaction()

Checking whether there is an H2O instance running at http://localhost:54321 . connected.

--------------------------  ------------------------------------------------------------------
H2O_cluster_uptime:         1 hour 4 mins
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.32.1.4
H2O_cluster_version_age:    6 days
H2O_cluster_name:           H2O_from_python_unknownUser_e86ayq
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    2.987 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
H2O_API_Extensions:         Amazon S3, XGBoost, Algos, AutoML, Core V3, TargetEncoder, Core V4
Python_version:             3.7.10 final
--------------------------  ------------------------------------------------------------------

Parse progress: |█████████████████████████████████████████████████████████| 100%
Parse progress: |█████████████████████████████████████████████████████████| 100%
gbm Model Build progress: |███████████████████████████████████████████████| 100%
WARNING: The `auc_type` parameter is set but it is not used because the `test_data` parameter is None.
gbm prediction progress: |████████████████████████████████████████████████| 100%

In [36]:
perf

ModelMetricsBinomial: gbm
** Reported on train data. **

MSE: 1.0522502836561015e-05
RMSE: 0.0032438407538843543
LogLoss: 0.0032435371251956766
Mean Per-Class Error: 0.0
AUC: 1.0
AUCPR: 1.0
Gini: 1.0

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.9969404398605609:

            -1      0 Error          Rate
0     -1  91.0    0.0   0.0    (0.0/91.0)
1      0   0.0  103.0   0.0   (0.0/103.0)
2  Total  91.0  103.0   0.0   (0.0/194.0)

Maximum Metrics: Maximum metrics at their respective thresholds

                         metric  threshold  value  idx
0                        max f1   0.996940    1.0  0.0
1                        max f2   0.996940    1.0  0.0
2                  max f0point5   0.996940    1.0  0.0
3                  max accuracy   0.996940    1.0  0.0
4                 max precision   0.996940    1.0  0.0
5                    max recall   0.996940    1.0  0.0
6               max specificity   0.996940    1.0  0.0
7              max absolute_mcc   0.996940    1.0  0.0
8    max min_per_class_accuracy   0.996940    1.0  0.0
9   max mean_per_class_accuracy   0.996940    1.0  0.0
10                      max tns   0.996940   91.0  0.0
11                      max fns   0.996940    0.0  0.0
12                      max fps   0.003441   91.0  1.0
13                      max tps   0.996940  103.0  0.0
14                      max tnr   0.996940    1.0  0.0
15                      max fnr   0.996940    0.0  0.0
16                      max fpr   0.003441    1.0  1.0
17                      max tpr   0.996940    1.0  0.0

Gains/Lift Table: Avg response rate: 53.09 %, avg score: 53.09 %

   group  cumulative_data_fraction  ...  cumulative_gain  kolmogorov_smirnov
0      1                  0.530928  ...        88.349515                 1.0
1      2                  1.000000  ...         0.000000                 0.0

[2 rows x 14 columns]

In [37]:
pred

predict,p-1,p0
0,0.00305956,0.99694
-1,0.996559,0.00344054
0,0.00305956,0.99694
0,0.00305956,0.99694
0,0.00305956,0.99694
0,0.00305956,0.99694
-1,0.996559,0.00344054
0,0.00305956,0.99694
0,0.00305956,0.99694
0,0.00305956,0.99694